---
title: "Exploration"
author: "Mariah Loehr"
date: "2024-06-10"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'hide')
library(tidyverse)
library(plotly)
library(packcircles)

taxon <- read.delim("taxon.txt") %>%
  na.omit() %>%
  pivot_longer(
    cols = X1:X103,
    names_to = "SampleID",
    values_to = "Abundance"
  ) %>%
  mutate(SampleID = as.integer(str_sub(SampleID, 2))) %>%
  mutate(Percentage = Abundance/100)

metadata <- read.delim("metadata.txt") %>%
  na.omit()

full_data <- metadata %>% 
  full_join(taxon, by = "SampleID") %>%
  group_by(SampleID) %>%
  arrange(desc(Abundance), .by_group = T) %>%
  mutate(Gender = ifelse(Gender == 1, "Homme", "Femme"))

phylum_data_full <- full_data %>%
  filter(str_detect(clade_name, "p_")) %>%
  filter(!str_detect(clade_name, "c_|o_|f_|g_|s_|_unclassified")) %>% #add to rest
  mutate(Phylum = str_sub(str_extract(clade_name, "p_.*"), 4))
```

```{r filter for specific id}
id = "1"
taxon_id <- taxon %>%
  filter(SampleID == id)
```

```{r donut charts}
## phylum donut chart
phylum_data <- data_id %>%
  filter(str_detect(clade_name, "p_")) %>%
  filter(!str_detect(clade_name, "c_|o_|f_|g_|s_")) %>%
  mutate(Phylum = gsub("_unclassified", "", str_sub(str_extract(clade_name, "p_*"), 4)))

phylum_donut <- phylum_data %>%
  plot_ly(labels = ~Phylum, values = ~Percentage,
          textposition = "inside",
          # textinfo = ifelse(Percentage < 1, "", "label"),
          hoverinfo = "label+percent") %>%
  add_pie(hole = 0.6) %>%
  layout(title = "Donut Phylum Chart", showlegend = F,
         xaxis = list(showgrid = F, zeroline = F, showticklabels = F),
         yxis = list(showgrid = F, zeroline = F, showticklables = F))
  

## family donut chart (top 10)
family_data <- data_id %>%
  filter(str_detect(clade_name, "f_")) %>%
  filter(!str_detect(clade_name, "g_|s_")) %>%
  group_by(clade_name = ifelse(row_number() < 10, clade_name = "Autres")) %>%
  summarise(across(c(Abundance, Percentage), sum)) %>%
  mutate(Family = ifelse(clade_name == "Autres", "Autres", 
                         str_sub(str_extract(clade_name, "f_*"), 4))) 

family_donut <- family_data %>%
  plot_ly(labels = ~Family, values = ~Percentage,
          textposition = "inside",
          # textinfo = ifelse(Percentage < 1, "", "label"),
          hoverinfo = "label+percent") %>%
  add_pie(hole = 0.6) %>%
  layout(title = "Donut Family Chart", showlegend = F,
         xaxis = list(showgrid = F, zeroline = F, showticklabels = F),
         yxis = list(showgrid = F, zeroline = F, showticklables = F))

## genre donut chart (top 15)
genre_data_donut <- data_id %>%
  filter(str_detect(clade_name, "g_")) %>%
  filter(!str_detect(clade_name, "s_")) %>%
  group_by(clade_name = ifelse(row_number() < 20, clade_name = "Autres")) %>%
  mutate(Genre = ifelse(clade_name == "Autres", "Autres", 
                         str_sub(str_extract(clade_name, "g_*"), 4))) 

genre_donut <- genre_data_donut %>%
  plot_ly(labels = ~Genre, values = ~Percentage,
          textposition = "inside",
          # textinfo = ifelse(Percentage < 1, "", "label"),
          hoverinfo = "label+percent") %>%
  add_pie(hole = 0.6) %>%
  layout(title = "Donut Genre Chart", showlegend = F,
         xaxis = list(showgrid = F, zeroline = F, showticklabels = F),
         yxis = list(showgrid = F, zeroline = F, showticklables = F))
```

```{r bar chart data explore}
bar_data <- function(id) {
  data_id <- phylum_data_full %>%
    filter(SampleID == as.character(id))
 
  phylum_data_pop <- phylum_data_full %>%
    group_by(Phylum) %>%
    summarise(across(Abundance, sum)) %>%
    mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
    mutate(Group = "Total Population")
 
  phylum_data_ID <- phylum_data_full %>%
    filter(SampleID == as.character(id)) %>%
    group_by(Phylum) %>%
    summarise(across(Abundance, sum)) %>%
    mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
    mutate(Group = "ID")
 
  phylum_data_bar <- rbind(phylum_data_ID, phylum_data_pop)
 
  for (group in c("Gender", "Age_class", "Region")) {
    phylum_data_bar <- phylum_data_full %>%
      filter_at(group, ~ . == data_id[[group]][[1]]) %>%
      group_by(Phylum) %>%
      summarise(across(Abundance, sum)) %>%
      mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
      mutate(Group = data_id[[group]][[1]]) %>%
      rbind(phylum_data_bar)
  }
  return(phylum_data_bar %>%
           mutate(Group = fct_relevel(
             Group, c("ID", "Total Population", 
                      data_id[["Gender"]][[1]], data_id[["Age_class"]][[1]], data_id[["Region"]][[1]])
           )))
}

all_bars <- bar_data(1) %>%
  ggplot(aes(fill = Phylum, y = Abundance, x = Group,
             text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%"))) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_viridis(option = "plasma", discrete = T)
ggplotly(all_bars, tooltip = "text")
##reorder bars
```

```{r bubble chart}
genre_data <- data_id %>%
  filter(str_detect(clade_name, "g_")) %>%
  filter(!str_detect(clade_name, "s_")) %>%
  mutate(genre = gsub("_unclassified","", str_sub(str_extract(clade_name, "g_*"), 4)))

packing <- circleProgressiveLayout(genre_data$Abundance, sizetype = 'area')
bubble_data = cbind(genre_data, packing)
plotcard <- circleLayoutVertices(packing, npoints = 50)

plotcard$Abundance <- rep(bubble_data$Abundance, each = 51)

bubble <- ggplot() +
  geom_polygon(data = plotcard, aes(x, y, group = id, fill = Abundance,
                                    text = paste(genre, "\n", str_sub(Abundance, 1, 4), "%")), 
               color = "black", alpha = 0.7) +
  scale_fill_viridis() +
  geom_text(data = bubble_data, aes(x,y,size=Abundance, 
                                    label= ifelse(Abundance < 0.5, "", paste0(genre)),
                                    text = paste(genre, "\n", str_sub(Abundance, 1, 4), "%"))) +
  scale_size_continuous(range = c(1,4)) +
  theme_void() +
  theme(legend.position = "none") +
  coord_equal()

bubble 

ggplotly(bubble)
```

```{r ggtree}
something <- system.file()
tree <- read.tree(something)

ggtree(tree, aes(color=group), layout = 'circular') + 
  geom_tiplab(size = 1, aes(angle = angle))
```

```{r shiny table}

```

```{r old code}
## phylum donut chart
# phylum_data <- data_id %>%
#   filter(str_detect(clade_name, "p_")) %>%
#   filter(!str_detect(clade_name, "c_|o_|f_|g_|s_")) %>%
#   mutate(Phylum = gsub("_unclassified", "", str_sub(str_extract(clade_name, "p_*"), 4))) %>%
#   mutate(ymax = cumsum(Percentage)) 
# phylum_data <- phylum_data %>%
#   mutate(ymin = c(0, head(phylum_data$ymax, n=-1)))
# 
# phylum_donut <- phylum_data %>%
#   ggplot(aes(ymax=ymax, ymin=ymin, xmax = 4, xmin=3, fill = Phylum,
#              text = Phylum)) +
#   geom_rect() +
#   coord_polar(theta = "y") +
#   xlim(c(2,4)) +
#   theme_void() +
#   scale_fill_discrete()
# 
# ## family donut chart (top 10)
# family_data <- data_id %>%
#   filter(str_detect(clade_name, "f_")) %>%
#   filter(!str_detect(clade_name, "g_|s_")) %>%
#   group_by(clade_name = ifelse(row_number() < 10, clade_name = "Autres")) %>%
#   summarise(across(c(Abundance, Percentage), sum)) %>%
#   mutate(Family = ifelse(clade_name == "Autres", "Autres", 
#                          gsub("_unclassified", "", str_sub(str_extract(clade_name, "f_*"), 4)))) %>%
#   mutate(ymax = cumsum(Percentage)) 
# family_data <- family_data %>%
#   mutate(ymin = c(0, head(family_data$ymax, n=-1)))
# 
# family_donut <- family_data %>%
#   ggplot(aes(ymax=ymax, ymin=ymin, xmax = 4, xmin=3, fill = Family,
#              text = paste(str_split(Family, "p_", simplify = T)[,2]))) +
#   geom_rect() +
#   coord_polar(theta = "y") +
#   xlim(c(2,4)) +
#   theme_void() +
#   scale_fill_discrete()
# 
# ## genre donut chart (top 15)
# genre_data_donut <- data_id %>%
#   filter(str_detect(clade_name, "g_")) %>%
#   filter(!str_detect(clade_name, "s_")) %>%
#   group_by(clade_name = ifelse(row_number() < 15, clade_name = "Autres")) %>%
#   mutate(Genre = ifelse(clade_name == "Autres", "Autres", 
#                          gsub("_unclassified", "", str_sub(str_extract(clade_name, "g_*"), 4)))) %>%
#   summarise(across(c(Abundance, Percentage), sum)) %>%
#   mutate(ymax = cumsum(Percentage)) 
# genre_data_donut <- genre_data_donut %>%
#   mutate(ymin = c(0, head(genre_data_donut$ymax, n=-1)))
# 
# genre_donut <- genre_data_donut %>%
#   ggplot(aes(ymax=ymax, ymin=ymin, xmax = 4, xmin=3, fill = Genre,
#              text = paste(str_split(Genre, "p_", simplify = T)[,2]))) +
#   geom_rect() +
#   coord_polar(theta = "y") +
#   xlim(c(2,4)) +
#   theme_void() +
#   scale_fill_discrete()


## bar chart ##

# phylum_data_bar <- phylum_data %>%
#   mutate(ymax = cumsum(Percentage))
# phylum_data_bar <- phylum_data_bar %>%
#   mutate(ymin = c(0, head(phylum_data_bar$ymax, n = -1)))
# 
# bar_nutrinaute <- phylum_data_bar %>%
#   ggplot(aes(ymax = ymax, ymin = ymin, xmax = 1, xmin = 0,
#              fill = Phylum, 
#              text = paste(Phylum))) +
#   geom_rect() +
#   scale_fill_discrete()

# bar_nutrinaute <- phylum_data %>%
#   ggplot(aes(fill = Phylum, y = Percentage, x = SampleID), 
#          text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%")) +
#   geom_bar(position = "fill", stat = "identity")
# ggplotly(bar_nutrinaute, tooltip = "text")
# 
# bar_pop <- phylum_data_full %>%
#   group_by(Phylum) %>%
#   summarise(across(c(Abundance, Percentage), sum)) %>%
#   mutate(Abundance = Abundance/sum(Abundance)*100) %>%
#   mutate(Percentage = Percentage/sum(Percentage)) %>%
#   mutate(dummy = "Pop") %>%
#   ggplot(aes(fill = Phylum, y = Percentage, x = SampleID), 
#          text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%")) +
#   geom_bar(position = "fill", stat = "identity")
# ggplotly(bar_pop, tooltip = "text")
#   
# bar_sexe <- phylum_data_full %>%
#   filter(Gender == 1) %>%
#   group_by(Phylum) %>%
#   summarise(across(c(Abundance, Percentage), sum)) %>%
#   mutate(Abundance = Abundance/sum(Abundance)*100) %>%
#   mutate(Percentage = Percentage/sum(Percentage)) %>%
#   mutate(dummy = "Gender") %>%
#   ggplot(aes(fill = Phylum, y = Percentage, x = SampleID), 
#          text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%")) +
#   geom_bar(position = "fill", stat = "identity")
# ggplotly(bar_sexe, tooltip = "text")
# 
# bar_age <- phylum_data_full %>%
#   filter(Age == "50-59") %>%
#   group_by(Phylum) %>%
#   summarise(across(c(Abundance, Percentage), sum)) %>%
#   mutate(Abundance = Abundance/sum(Abundance)*100) %>%
#   mutate(Percentage = Percentage/sum(Percentage)) %>%
#   mutate(dummy = "Age") %>%
#   ggplot(aes(fill = Phylum, y = Percentage, x = SampleID), 
#          text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%")) +
#   geom_bar(position = "fill", stat = "identity")
# ggplotly(bar_age, tooltip = "text")
# 
# bar_region <- phylum_data_full %>%
#   filter(Region == "A") %>%
#   group_by(Phylum) %>%
#   summarise(across(c(Abundance, Percentage), sum)) %>%
#   mutate(Abundance = Abundance/sum(Abundance)*100) %>%
#   mutate(Percentage = Percentage/sum(Percentage)) %>%
#   mutate(dummy = "Region") %>%
#   ggplot(aes(fill = Phylum, y = Percentage, x = SampleID), 
#          text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%")) +
#   geom_bar(position = "fill", stat = "identity")
# ggplotly(bar_pop, tooltip = "text")

## pre-function bar charts ##
# phylum_data_sex <- phylum_data_full %>%
#   filter(Gender == 1) %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = ifelse(phylum_data$Gender[1] == 1, "Homme", "Femme"))
# 
# phylum_data_age <- phylum_data_full %>%
#   filter(Age_class == "50-59") %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = phylum_data$Age_class[1])
# 
# phylum_data_region <- phylum_data_full %>%
#   filter(Region == "A") %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = phylum_data$Region[1])
# 
# phylum_data_pop <- phylum_data_full %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = "Total Population")
# 
# phylum_data_ID <- phylum_data_full %>%
#   filter(SampleID == 1) %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = "ID")
# 
# phylum_data_bar <- rbind(phylum_data_ID, phylum_data_pop,
#                          phylum_data_sex, phylum_data_age, phylum_data_region)
# 
# all_bars <- phylum_data_bar %>%
#   ggplot(aes(fill = Phylum, y = Abundance, x = Group,
#              text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%"))) +
#   geom_col(position = "fill", stat = "identity") +
#   scale_color_viridis(option = "plasma", discrete = T)
# ggplotly(all_bars, tooltip = "text")


### bar chart function first draft ###

# bar_data <- function(group, id){
#   data_id <- phylum_data_full %>%
#     filter(SqmpleID == as.character(id))
#   
#   return(phylum_data_full %>%
#            filter_at(group, ~ . == data_id[[group]][[1]]) %>%
#            group_by(Phylum) %>%
#            summarise(across(Abundance, sum)) %>%
#            mutate(Abundance/sum(Abundance)*100) %>%
#            mutate(Group = data_id[[group]][[1]])
#   )
# }
# 
# phylum_data_pop <- phylum_data_full %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = "Total Population")
# 
# #fix##
# phylum_data_ID <- phylum_data_full %>%
#   filter(SampleID == 1) %>%
#   group_by(Phylum) %>%
#   summarise(across(Abundance, sum)) %>%
#   mutate(Abundance = (Abundance/sum(Abundance))*100) %>%
#   mutate(Group = "ID")
# 
# phylum_data_bar <- rbind(phylum_data_ID, phylum_data_pop,
#                          bar_data("Gender", 1), bar_data("Gender", 1), bar_data("Gender", 1))
# 
# all_bars <- phylum_data_bar %>%
#   ggplot(aes(fill = Phylum, y = Abundance, x = Group,
#              text = paste(Phylum, "\n", str_sub(Abundance, 1, 4), "%"))) +
#   geom_col(position = "fill", stat = "identity") +
#   scale_color_viridis(option = "plasma", discrete = T)
# ggplotly(all_bars, tooltip = "text")
```
